### ISSUE TITLE
FORMAT DATE ERROR

### ISSUE THREAD

**Issue by Periter** [FesonX/JobCrawler#1]
day = ''.join(item['create_time'])
TypeError: can only join an iterable
line 208 in pipeline.py
Another error is the create time always be the same

**Comment by FesonX** [comment]
Which Python Ver. do U use

**Comment by FesonX** [comment]
I haven't found this problem, I just found a datetime convert ERROR, and I had fixed it just now.
your problem i think perhaps type(item['create_time']) is a list or other iterable type.

you can try `str(item['create_time'])` before join.
